### ISSUE TITLE
Catalog Schema Review

### ISSUE THREAD

**Issue by silvester-pari** [ESA-EarthCODE/open-science-catalog-metadata#232]
@silvester-pari and Fabian to review the latest schema used for validating updates to the OSC via GitHub.

**Comment by silvester-pari** [comment]
The following discussion points have been identified:

- [ ] `null` for time interval items: although generally not optimal, because of the nature of the current state of OSC it is necessary to allow this. Validation has been updated: https://github.com/EOEPCA/open-science-catalog-metadata-testing/commit/c6ab8cc724729726b5ec3ffcd07cbbded775428d
- [ ] enforcing `title` for links: this is a best practice and should be required. validation has been changed in https://github.com/EOEPCA/open-science-catalog-metadata-testing/commit/36401af416d82fc1f8a7e02830c48ee46d950be7 and updates to the metadata repository is proposed in https://github.com/ESA-EarthCODE/open-science-catalog-metadata/pull/231 (only links missing title were `cite-as` links)
- [ ] relative hierarchical links: should be allowed, updated validation in https://github.com/EOEPCA/open-science-catalog-metadata-testing/commit/3af27d384de78a169ae85c0829df9336d51135a4; technical debt in the dynamic backend GUI accepted
- [ ] referencing other OSC entities (such as `variables`, `themes`, `eo-missions` etc.) via `id` instead of `title`
- [ ] removing the additional step of OSC builder: since it is accepted that STAC Browser is the main catalog rendering and search is currently done on the client, it is possible to remove the builder step and directly ingest the "source of truth" catalog into the dynamic catalog (with dedicated validation workflow). This makes the entire process easier to understand for external users and removes one of the "moving parts". In order to keep the functionality for the user to link from one entity to another, an extension to the rendering of certain properties inside STAC Browser is needed: https://github.com/EOEPCA/open-science-catalog-frontend/issues/435

**Comment by silvester-pari** [comment]
The following discussion points have been identified:

- [ ] `null` for time interval items: although generally not optimal, because of the nature of the current state of OSC it is necessary to allow this. Validation has been updated: https://github.com/EOEPCA/open-science-catalog-metadata-testing/commit/c6ab8cc724729726b5ec3ffcd07cbbded775428d
- [ ] enforcing `title` for links: this is a best practice and should be required. validation has been changed in https://github.com/EOEPCA/open-science-catalog-metadata-testing/commit/36401af416d82fc1f8a7e02830c48ee46d950be7 and updates to the metadata repository is proposed in https://github.com/ESA-EarthCODE/open-science-catalog-metadata/pull/231 (only links missing title were `cite-as` links)
- [ ] relative hierarchical links: should be allowed, updated validation in https://github.com/EOEPCA/open-science-catalog-metadata-testing/commit/3af27d384de78a169ae85c0829df9336d51135a4; technical debt in the dynamic backend GUI accepted
- [ ] referencing other OSC entities (such as `variables`, `themes`, `eo-missions` etc.) via `id` instead of `title`
- [ ] removing the additional step of OSC builder: since it is accepted that STAC Browser is the main catalog rendering and search is currently done on the client, it is possible to remove the builder step and directly ingest the "source of truth" catalog into the dynamic catalog (with dedicated validation workflow). This makes the entire process easier to understand for external users and removes one of the "moving parts". In order to keep the functionality for the user to link from one entity to another, an extension to the rendering of certain properties inside STAC Browser is needed: https://github.com/EOEPCA/open-science-catalog-frontend/issues/435

**Comment by silvester-pari** [comment]
Validation issues to tackle:

- [ ] multiple hrefs in one link, example: https://github.com/ESA-EarthCODE/open-science-catalog-metadata/blob/fd4577bd53fc86655668ebf653d0bb4316c4d1d8/variables/ammonia/catalog.json#L15
- [ ] "via" links without `href`
- [ ] overview catalogs (e.g. variables/catalog.json) missing links to actual variables

**Comment by GarinSmith** [comment]
As agreed, when ready please provide a reference  to: 
i) the location of the latest schema validation file.
ii) the readme containing a formal definition of any validation needed in addition to above.
This can then be provided to any platforms that need this information. 
If appropriate, we might also add some code to support ii) above (good idea by the way), but this depends on the nature of ii) and what the platforms can use.

**Comment by silvester-pari** [comment]
Validation now passing in this repository, validation schema/script has been set up at https://github.com/ESA-EarthCODE/open-science-catalog-validation.
