### ISSUE TITLE
Missing "via" links for some products

### ISSUE THREAD

**Issue by silvester-pari** [ESA-EarthCODE/open-science-catalog-metadata#280]
The following products have missing "via" links:

-   'dem-antarctica-2013-lpf-mitap'
-   'dem-antarctica-2017-lpf-mitap'
-   'glacier-elevation-cryosat-mountain-glaciers'
-   'glacier-mass-balance-lpf-mitap' [](https://doi.pangaea.de/10.1594/PANGAEA.964536?format=html)
-   'model-ionosphere-4dionosphere'
-   's2l2a-uncertainty-sr-lpf-l2arut'
-   'surface-elevation-change-lpf-mitap'

This is currently reflected in the validation (turned off as a strict requirement currently), but solving these issues will allow us to enable the strict validation again.

**Comment by edobrowolska** [comment]
Silvester, I contscted the project responsible person to provide us with links to: 
- 'dem-antarctica-2013-lpf-mitap'
- 'dem-antarctica-2017-lpf-mitap'
- 'glacier-mass-balance-lpf-mitap'
- 'surface-elevation-change-lpf-mitap'
I'm not sure how long it will take, but hopefully soon we will get the information to update the links to access datasets.

**Comment by silvester-pari** [comment]
The missing "via" links were added.
